### ISSUE TITLE
SD Implementation 

### ISSUE THREAD

**Issue by fballan93** [happychriss/MKR_VoiceRecognition#1]
First Allow me to show my gratitude for such huge effort that has been poured into this project it helped me a lot since it was the only one available online. I tried digging into the code to alter some stuff to suit my application. however, I was wondering if the code is compatible if I want to use it to store the data on an SD card and if you can help me. sorry, I'm new to all this Arduino world and I was seeking help.

**Comment by happychriss** [comment]
Hi, thx for your feedback. Please note, that I am not active maintaining this project any more.  As I know the Goolge Speech API has changed the interface and the code needs to be adjusted.
The trick on this demo-program is *not* to need an SD card, but directly sending the speech data to Google for recognition - so even a small Android device can handle speech recognition.
